---
- name: Download and install the Elasticsearch package manually
  hosts: all
  become: true
  vars:
    es_dir: "/opt/tools/es"
    es_ver: "7.17.23"

  tasks:

    - name: Install dependencies packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - net-tools
          - jq
          - tree
          - wget
          - python3
        update_cache: true

    - name: Create elasticsearch directory
      ansible.builtin.file:
        path: "{{ es_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0775"

    - name: Download .deb with version {{ es_ver }}
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ es_dir }}"
        mode: "0755"
      with_items:
        - "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_ver }}-amd64.deb"
        - "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_ver }}-amd64.deb.sha512"

    - name: Use sha512 to calculate the checksum
      ansible.builtin.stat:
        path: "{{ es_dir }}/elasticsearch-{{ es_ver }}-amd64.deb.sha512"
        checksum_algorithm: sha512

    - name: Install a .deb package
      ansible.builtin.apt:
        deb: "{{ es_dir }}/elasticsearch-{{ es_ver }}-amd64.deb"
