---
- name: Download and install the Elasticsearch
  hosts: all
  become: true
  vars:
    es_dir: "/opt/elasticsearch"
    es_work_dir: "{{ es_dir }}/running"
    es_setup_dir: "{{ es_dir }}/setup"
    es_log_dir: "{{ es_dir }}/log"
    es_backup_dir: "{{ es_dir }}/backup"
    es_ver: "7.10.1"

  tasks:
    - name: Install dependencies packages
      ansible.builtin.shell: |
        apt update
        apt install -y apt-transport-https net-tools jq tree wget python3
      register: install_dependencies_data
      changed_when: install_dependencies_data.rc != 0

    - name: Check ES directories exists
      ansible.builtin.stat:
        path: "{{ item }}"
      register: es_dirs_data
      loop:
        - "{{ es_dir }}"
        - "{{ es_work_dir }}"
        - "{{ es_setup_dir }}"
        - "{{ es_log_dir }}"
        - "{{ es_backup_dir }}"

    - name: Create ES directories if it not exists
      ansible.builtin.file:
        path: "{{ item.item }}"
        state: directory
        owner: root
        group: root
        mode: "0775"
      loop: "{{ es_dirs_data.results }}"
      when: not item.stat.exists

    - name: Check ES setup directory exists
      ansible.builtin.stat:
        path: "{{ es_setup_dir }}"
      register: es_setup_dir_data

    - name: Check ES setup file exists
      ansible.builtin.stat:
        path: "{{ es_setup_dir }}/elasticsearch-{{ es_ver }}-amd64.deb"
      register: es_setup_file_data

    - name: Download .deb file if it not exists
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_ver }}-amd64.deb"
        dest: "{{ es_setup_dir }}/elasticsearch-{{ es_ver }}-amd64.deb"
        checksum: "sha512:https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_ver }}-amd64.deb.sha512"
        mode: "0755"
        validate_certs: false
      when: es_setup_dir_data.stat.exists and not es_setup_file_data.stat.exists

    - name: Get packages
      ansible.builtin.shell: |
        dpkg-query -f '${binary:Package}\n' -W
      register: packages
      changed_when: packages.rc != 0

    - name: Print packages
      ansible.builtin.debug:
        msg: "{{ packages | community.general.json_query(\"stdout_lines[?contains(@, 'elasticsearch')]\") }}"

    # - name: Install ES with .deb package
    #   ansible.builtin.shell: |
    #     dpkg -i {{ es_setup_dir }}/elasticsearch-{{ es_ver }}-amd64.deb
    #   when: packages | community.general.json_query("stdout_lines[?contains(@, 'elasticsearch')]") != ""
    #   register: es_deb
    #   changed_when: es_deb.rc != 0

    # - name: Print 2
    #   ansible.builtin.debug:
    #     var: es_deb
