---

- name: Configure ES node 1
  hosts: ts-prd-01
  become: true
  vars:
    es_cluster: "es-for-data"
    es_name: "es-prd-01"
    es_ip: "192.168.1.20"
    es_port: "9200"
    es_user: "elastic"
    es_pass: "dnsdud2022!"
    es_bin: "/usr/share/elasticsearch/bin"
  tasks:

    - name: Change configure
      ansible.builtin.lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regex: "{{ regex }}"
        line: "{{ line }}"
      loop:
        - { regex: '^#cluster.name:', line: 'cluster.name: {{ es_cluster }}' }
        - { regex: '^#node.name:', line: 'node.name: {{ es_name }}' }
        - { regex: '^#network.host:', line: 'network.host: {{ es_ip }}' }
        - { regex: '^#http.port:', line: 'http.port: {{ es_port }}' }
        - { regex: '^#transport.host:', line: 'transport.host: 0.0.0.0' }
        - { regex: '^#discovery.seed_hosts:', line: 'discovery.seed_hosts:' }
      register: configure

    - name: Start Elasticsearch Service
      ansible.builtin.systemd_service:
        name: elasticsearch
        state: started
      when: configure.changed

    - name: Reset elasticsearch password
      ansible.builtin.shell:
        chdir: {{ es_bin }}
        cmd: echo " {{ es_pass }} " | ./elasticsearch-reset-password -i -u {{ es_user }} --stdin

    - name: Check status
      ansible.builtin.command:
        cmd: curl -k -u {{ es_user }}:{{ es_pass }} https://{{ es_ip }}:{{ es_port }}/
      register: check_status1

    - name: Check status cluster
      ansible.builtin.command:
        cmd: curl -k -u {{ es_user }}:{{ es_pass }} https://{{ es_ip }}:{{ es_port }}/_cluster/health?pretty
      register: check_status2

    - name: Create file elasticsearch-enrollment-token
      ansible.builtin.file:
        path: "{{ es_bin }}/elasticsearch-enrollment-token"
        owner: elasticsearch
        group: elasticsearch
        mode: "0644"
      delegate_to: localhost

    - name: Create elasticsearch token for joining from other nodes
      ansible.builtin.command:
        cmd: ./elasticsearch-create-enrollment-token -s node
      register: create_token
      args:
        chdir: "{{ es_bin }}"

    - name: Print elasticsearch token to file
      ansible.builtin.copy:
        content: "{{create_token.stdout}}"
        dest: "{{ es_bin }}/elasticsearch-enrollment-token"
      delegate_to: localhost
